//! Integration tests against reference data generated by the original C++
//! Ptex library (see `tests/fixtures/`).
//!
//! For each fixture, the C++ library wrote a `.ptx` file with `PtexWriter`
//! and dumped what its own `PtexReader` returns:
//! - `<name>.info.txt`: header fields, per-face info, and meta data
//! - `<name>.faces.dat`: full-resolution `getData` output for every face
//! - `<name>.reduced.dat`: `getData` output at two reduced resolutions per
//!   face (one symmetric/stored, one dynamically computed)
//! - `<name>.pixels.txt`: `getPixel` float samples

use std::fmt::Write as _;
use std::path::PathBuf;

use ptex::{MeshType, MetaDataType, PtexReader, Res};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// Render the reader's view of a file in the same text format as the C++
/// dump in `<name>.info.txt`.
fn render_info(tx: &mut PtexReader) -> String {
    let mut out = String::new();
    writeln!(out, "meshtype {}", tx.mesh_type().name()).unwrap();
    writeln!(out, "datatype {}", tx.data_type().name()).unwrap();
    writeln!(out, "alphachan {}", tx.alpha_channel()).unwrap();
    writeln!(out, "nchannels {}", tx.num_channels()).unwrap();
    writeln!(out, "nfaces {}", tx.num_faces()).unwrap();
    writeln!(out, "hasmipmaps {}", tx.has_mip_maps() as u8).unwrap();
    for f in 0..tx.num_faces() {
        let fi = *tx.face_info(f).unwrap();
        writeln!(
            out,
            "face {} res {} {} adjfaces {} {} {} {} adjedges {} {} {} {} flags {}",
            f,
            fi.res.ulog2,
            fi.res.vlog2,
            fi.adjfaces[0],
            fi.adjfaces[1],
            fi.adjfaces[2],
            fi.adjfaces[3],
            fi.adjedge(0) as u8,
            fi.adjedge(1) as u8,
            fi.adjedge(2) as u8,
            fi.adjedge(3) as u8,
            fi.flags,
        )
        .unwrap();
    }
    let meta = tx.metadata().unwrap().clone();
    for entry in meta.iter() {
        write!(out, "meta {} {}", entry.key(), entry.data_type().name()).unwrap();
        match entry.data_type() {
            MetaDataType::String => write!(out, " {}", entry.as_str().unwrap()).unwrap(),
            MetaDataType::Int8 => {
                for v in entry.as_i8().unwrap() {
                    write!(out, " {v}").unwrap();
                }
            }
            MetaDataType::Int16 => {
                for v in entry.as_i16().unwrap() {
                    write!(out, " {v}").unwrap();
                }
            }
            MetaDataType::Int32 => {
                for v in entry.as_i32().unwrap() {
                    write!(out, " {v}").unwrap();
                }
            }
            MetaDataType::Float => {
                for v in entry.as_f32().unwrap() {
                    write!(out, " {}", fmt_g(v as f64)).unwrap();
                }
            }
            MetaDataType::Double => {
                for v in entry.as_f64().unwrap() {
                    write!(out, " {}", fmt_g(v)).unwrap();
                }
            }
        }
        writeln!(out).unwrap();
    }
    out
}

/// Format a float like C's `%g` (shortest representation, no trailing
/// zeros) closely enough for the values used in the fixtures.
fn fmt_g(v: f64) -> String {
    if v == v.trunc() && v.abs() < 1e15 {
        format!("{}", v as i64)
    } else {
        format!("{v}")
    }
}

fn check_fixture(name: &str) {
    let mut tx = PtexReader::open(fixture(&format!("{name}.ptx"))).unwrap();

    // header, face info, and meta data
    let expected_info = std::fs::read_to_string(fixture(&format!("{name}.info.txt"))).unwrap();
    assert_eq!(render_info(&mut tx), expected_info, "{name}: info mismatch");

    // full-resolution face data
    let expected_faces = std::fs::read(fixture(&format!("{name}.faces.dat"))).unwrap();
    let mut got = Vec::new();
    for f in 0..tx.num_faces() {
        got.extend_from_slice(&tx.get_data(f).unwrap());
    }
    assert_eq!(got.len(), expected_faces.len(), "{name}: face data size");
    assert!(got == expected_faces, "{name}: face data mismatch");

    // reduced-resolution face data (matches the reductions performed by
    // the dump program)
    let expected_reduced = std::fs::read(fixture(&format!("{name}.reduced.dat"))).unwrap();
    let tri = tx.mesh_type() == MeshType::Triangle;
    let mut got = Vec::new();
    for f in 0..tx.num_faces() {
        let res = tx.face_info(f).unwrap().res;
        let r1 = Res::new((res.ulog2 - 1).max(0), (res.vlog2 - 1).max(0));
        got.extend_from_slice(&tx.get_data_at_res(f, r1).unwrap());
        let r2 = if tri {
            Res::new((res.ulog2 - 2).max(0), (res.vlog2 - 2).max(0))
        } else {
            Res::new((res.ulog2 - 2).max(0), (res.vlog2 - 1).max(0))
        };
        got.extend_from_slice(&tx.get_data_at_res(f, r2).unwrap());
    }
    assert_eq!(
        got.len(),
        expected_reduced.len(),
        "{name}: reduced data size"
    );
    assert!(got == expected_reduced, "{name}: reduced data mismatch");

    // pixel samples
    let pixels = std::fs::read_to_string(fixture(&format!("{name}.pixels.txt"))).unwrap();
    let nchan = tx.num_channels();
    for line in pixels.lines() {
        let mut it = line.split_whitespace();
        let f: usize = it.next().unwrap().parse().unwrap();
        let u: usize = it.next().unwrap().parse().unwrap();
        let v: usize = it.next().unwrap().parse().unwrap();
        let expected: Vec<f32> = it.map(|t| t.parse().unwrap()).collect();
        let got = tx.get_pixel(f, u, v, 0, nchan).unwrap();
        assert_eq!(got, expected, "{name}: pixel {f} ({u},{v}) mismatch");
    }
}

#[test]
fn quad_uint8_with_alpha_and_metadata() {
    check_fixture("quad_u8");
}

#[test]
fn quad_float_tiled() {
    check_fixture("quad_f32");
}

#[test]
fn quad_half() {
    check_fixture("quad_f16");
}

#[test]
fn triangle_uint16() {
    check_fixture("tri_u16");
}

#[test]
fn premultiplied_face_data() {
    let expected = std::fs::read(fixture("quad_u8.pmfaces.dat")).unwrap();
    let mut tx = PtexReader::open_with_options(fixture("quad_u8.ptx"), true).unwrap();
    let mut got = Vec::new();
    for f in 0..tx.num_faces() {
        got.extend_from_slice(&tx.get_data(f).unwrap());
    }
    assert!(got == expected, "premultiplied face data mismatch");
}

#[test]
fn not_a_ptex_file() {
    match PtexReader::open(fixture("quad_u8.info.txt")) {
        Err(ptex::Error::NotAPtexFile) => {}
        Err(e) => panic!("unexpected error: {e}"),
        Ok(_) => panic!("expected NotAPtexFile error"),
    }
}

#[test]
fn buffer_apis() {
    let mut tx = PtexReader::open(fixture("quad_u8.ptx")).unwrap();
    let res = tx.face_info(0).unwrap().res;
    let full = tx.get_data(0).unwrap();

    // get_data_into with a padded stride
    let rowlen = res.u() * tx.pixel_size();
    let stride = rowlen + 16;
    let mut padded = vec![0u8; stride * res.v()];
    tx.get_data_into(0, res, &mut padded, stride).unwrap();
    for v in 0..res.v() {
        assert_eq!(
            &padded[v * stride..v * stride + rowlen],
            &full[v * rowlen..(v + 1) * rowlen]
        );
    }

    // constant face data matches its constant pixel value
    let const_pixel = tx.constant_data(2).unwrap().to_vec();
    assert_eq!(const_pixel, vec![40, 80, 120, 200]);
    let const_face = tx.get_data(2).unwrap();
    for pix in const_face.chunks_exact(4) {
        assert_eq!(pix, &const_pixel[..]);
    }
}
